exclude:
 - Gruntfile.js
 - LICENCE
 - README.md
 - REFERENCE.md
 - jekyll-test.sh
 - node_modules
 - package.json
 - pre-commit
include:
 - .grunt
# GitHub defaults
safe: true
lsi: false
highlighter: pygments
