exclude:
 - Gemfile
 - Gemfile.lock
 - Gruntfile.js
 - LICENCE
 - README.md
 - REFERENCE.md
 - node_modules
 - package.json
 - pre-commit
include:
 - .grunt

# GitHub defaults
highlighter: pygments
safe: true
lsi: false
